### ISSUE TITLE
Практичний іспит на категорію B (Механічна коробка передач)

### ISSUE THREAD

**Issue by andlua22** [rnyPlanet/hsc-gov-ua-subscriber#1]
Можеш добавити взяття талонів на практичний іспит на категорію B (механічна коробка передач)

**Comment by rnyPlanet** [comment]
Таке вже є. Тільки там транспортний засіб навчального закладу

**Comment by tesla-maniak** [comment]
Можеш добавити транспортний засіб сервісного центру і на коробці автомат?)

**Comment by rnyPlanet** [comment]
> Можеш добавити транспортний засіб сервісного центру і на коробці автомат?)

Потрібен час. Як буде час, гляну що можна зробити, можливо завтра, але не обіцяю

**Comment by tesla-maniak** [comment]
Дякую, я пробував міняти айді, но нічого не вийшло.

**Comment by andlua22** [comment]
> Дякую, я пробував міняти айді, но нічого не вийшло.

Поїдеї якщо ти на сервісну машину, то потрібно прибрати sub_id, а question_id оставляєьться

**Comment by tesla-maniak** [comment]
Воно не дає вибрати інше окрім 56

**Comment by rnyPlanet** [comment]
> Воно не дає вибрати інше окрім 56

вони оновили сайт. тепер автоматизація не працює
