### ISSUE TITLE
Привіт

### ISSUE THREAD

**Issue by tesla-maniak** [rnyPlanet/hsc-gov-ua-subscriber#2]
Привіт! Хочу спробувати переробити систему, щоб брати талон на авто сервісного центру, але система не дозволяє внести зміни. Що потрібно виправити, можете підказати?

**Comment by rnyPlanet** [comment]
Думаю потрібно дізнатись [question_id](https://github.com/rnyPlanet/hsc-gov-ua-subscriber/blob/master/content/configs/config_file.md), та вписати в конфіг

**Comment by rnyPlanet** [comment]
вони оновили сайт. поки хз що можна зробити

**Comment by rnyPlanet** [comment]
оновив код. приклад для [Практичний іспит на категорію В (транспортний засіб сервісного центру з автоматичною коробкою передач)](https://github.com/rnyPlanet/hsc-gov-ua-subscriber/blob/master/content/configs/config_file.md#%D0%BF%D1%80%D0%B8%D0%BA%D0%BB%D0%B0%D0%B4-%D0%BA%D0%BE%D0%BD%D1%84%D1%96%D0%B3-%D1%84%D0%B0%D0%B9%D0%BB%D1%83-%D0%B4%D0%BB%D1%8F-%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D1%87%D0%BD%D0%B8%D0%B9-%D1%96%D1%81%D0%BF%D0%B8%D1%82-%D0%BD%D0%B0-%D0%BA%D0%B0%D1%82%D0%B5%D0%B3%D0%BE%D1%80%D1%96%D1%8E-%D0%B2-%D1%82%D1%80%D0%B0%D0%BD%D1%81%D0%BF%D0%BE%D1%80%D1%82%D0%BD%D0%B8%D0%B9-%D0%B7%D0%B0%D1%81%D1%96%D0%B1-%D1%81%D0%B5%D1%80%D0%B2%D1%96%D1%81%D0%BD%D0%BE%D0%B3%D0%BE-%D1%86%D0%B5%D0%BD%D1%82%D1%80%D1%83-%D0%B7-%D0%B0%D0%B2%D1%82%D0%BE%D0%BC%D0%B0%D1%82%D0%B8%D1%87%D0%BD%D0%BE%D1%8E-%D0%BA%D0%BE%D1%80%D0%BE%D0%B1%D0%BA%D0%BE%D1%8E-%D0%BF%D0%B5%D1%80%D0%B5%D0%B4%D0%B0%D1%87)

**Comment by tesla-maniak** [comment]
Дякую, буду дивитись)

**Comment by l1monenko** [comment]
Якщо я не помиляюсь, то на повідомлення про талон на сервісну машину не спрацює, бо трігер стоїть на [наступне](https://github.com/rnyPlanet/hsc-gov-ua-subscriber/blob/30cd58ae7842e3b5a0395d6939d43c0539e63243/hsc_gov_subscriber/__main__.py#L14)

А повідомлення виглядає так: 
![image](https://github.com/user-attachments/assets/aa747991-7866-4f2d-afab-c40d21f387ad)

Тож треба руцями трохи поправить код і по ідеї, воно буде працювати

**Comment by rnyPlanet** [comment]
Ок, завтра гляну якщо буде час. Або ти можеш поправити та створити pull request. І дай пліз текст повідомлення з тг

**Comment by tesla-maniak** [comment]
Не поправляли код?)

**Comment by l1monenko** [comment]
Ти можеш сам поправити, як тимчасове рішення

**Comment by tesla-maniak** [comment]
![{C8EC8019-76D1-43D1-B925-D3C1BA229836}](https://github.com/user-attachments/assets/28a66635-4cf0-4670-a8a3-5a2a94226e55)
тут поправлять надо?

**Comment by rnyPlanet** [comment]
> ![{C8EC8019-76D1-43D1-B925-D3C1BA229836}](https://private-user-images.githubusercontent.com/183943817/374991759-28a66635-4cf0-4670-a8a3-5a2a94226e55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NjAzMzQsIm5iZiI6MTcyODY2MDAzNCwicGF0aCI6Ii8xODM5NDM4MTcvMzc0OTkxNzU5LTI4YTY2NjM1LTRjZjAtNDY3MC1hOGEzLTVhMmE5NDIyNmU1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMVQxNTIwMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMjMwYmM5ZDE5ZTg2ZmJkOGVkZTkwOGVmYzlkNTQwMWJmY2U3OTliMWQ1Zjk0ZjA1MWM3OTBkMjBlZWU2MGQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.D8wE1HPiUg51RJMdA1dyRQcQ-THtZolKY72yHLj1AYs) тут поправлять надо?

І тут https://github.com/rnyPlanet/hsc-gov-ua-subscriber/blob/master/hsc_gov_subscriber/__main__.py#L14

**Comment by rnyPlanet** [comment]
> Якщо я не помиляюсь, то на повідомлення про талон на сервісну машину не спрацює, бо трігер стоїть на [наступне](https://github.com/rnyPlanet/hsc-gov-ua-subscriber/blob/30cd58ae7842e3b5a0395d6939d43c0539e63243/hsc_gov_subscriber/__main__.py#L14)
> 
> А повідомлення виглядає так: ![image](https://private-user-images.githubusercontent.com/146029723/374633622-aa747991-7866-4f2d-afab-c40d21f387ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTIyMjIsIm5iZiI6MTcyODcxMTkyMiwicGF0aCI6Ii8xNDYwMjk3MjMvMzc0NjMzNjIyLWFhNzQ3OTkxLTc4NjYtNGYyZC1hZmFiLWM0MGQyMWYzODdhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQwNTQ1MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZjMyMDMwODQ4ZjE0MTEyZTIxNzQwMjYxOTUzYmQ4NGE0OGMwOWM3M2RiMjQyNmY3OTk5Nzg5ZDcwZDA3OThhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.T_SuvP_w3LxY7se6onupmyvsGrzAdVIMELbxsB64nzg)
> 
> Тож треба руцями трохи поправить код і по ідеї, воно буде працювати

оновив

**Comment by tesla-maniak** [comment]
![Без имени](https://github.com/user-attachments/assets/92148d61-0035-4e9a-98b6-e2c320a91600)
Привіт, коли знаходить талон постійно б'є цю помилку, можешь підказати?

**Comment by rnyPlanet** [comment]
> ![Без имени](https://private-user-images.githubusercontent.com/183943817/379759650-92148d61-0035-4e9a-98b6-e2c320a91600.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NzM3OTYsIm5iZiI6MTcyOTc3MzQ5NiwicGF0aCI6Ii8xODM5NDM4MTcvMzc5NzU5NjUwLTkyMTQ4ZDYxLTAwMzUtNGU5YS05OGI2LWUyYzMyMGE5MTYwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQxMjM4MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NTVmMzRhNDI3MDc5ODZiZWQ3OGU1YjViMjEzNzlhOGQ2NzM4OWQ4ZTVlMTdiMDUwMTJlZTk3NWFkNTI1MDQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MgFcVThPjMZKrqWsIFt-_xcFMQfSH90D_756q-SWQ58) Привіт, коли знаходить талон постійно б'є цю помилку, можешь підказати?

Схоже хтось бере швидше) треба буде зробити рандомный вибір, а то зараз всі берут перший талон (якщо ще в когось запущений бот - у всіх бере перший талон). Як буде час - дороблю, є пару ідей

**Comment by rnyPlanet** [comment]
оновив. 
щоб перевірити (без повідомлення від тг) - мож змінити [текст](https://github.com/rnyPlanet/hsc-gov-ua-subscriber/blob/master/tests/main.py) та [конфігі](https://github.com/rnyPlanet/hsc-gov-ua-subscriber/blob/master/hsc_gov_subscriber/config.ini) (наприклад інший офіс де є вільний час).

**але НЕ БЕРІТЬ ТА НЕ ВІДМІНЯЙТЕ ПОСЛУГИ БІЛЬШЕ 4х РАЗІВ - БУДЕ БЛОКУВАННЯ НА 10 ДНІВ**
